# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

# command to deploy build to PyPi
deploy:
  provider: pypi
  user: "GaryCondon"
  password:
    secure: "rWL0bRpWdQ6nh35GpY1lhIbHMbZVvITXYbTenA8Yi1V04FeosSeOdAKrzbzJ3ux9ymt9rzwm4O2HDAl8c7IaUJ6flOZSRWarv6kU4/uiQOn1UY/+twfQR6LmmL5lun/8dROfbVWwhmufjhnvT9jyrhCu1d/nS8IL3IaF1QxUP7CPS1207zssSgbjysZj2oFBv1S2RjdktWAF+hCG+s95etUrm9g7QEnjZsq2NnMnMKYWEgois6x+qC717jFjRx18IFAwKbN4CjioiawAKCjFfgssFHkhc433Q1jsZik0zexFhFDrTrAjeeavkBlDGBSX1a5yNyL0KPU78O87qHOK2zCDwNtAoM4i4Hv4AO1E7nVHuG5KqsHDK8ccKd0nzzpwta7Nk/QkiaSfpc3cHpukD1cPE9bT6g3z+iPGzMZJNfVtV/wJZ6OgIIxz7fFscH+JNzjYLSUhfE5bfFzjM/bCBKWpfuqMpr2iKi+a24kreZzD2ZKYLWCkl1CugDS7mAgcXsKFT9e1MhiCWEJC8nrIJImaWZcNA08Xxcp9xgNxAOiKvYOUhxTI5BUW/AnSKsnHiHJl+arTaAc4Fdj0HT5u9G3s4aA0r9xDYqPHtoNaCS2V1JhuULp0RwXXbu3zT02RBuW8dfShaHOybCoyxl9e/5oCfSWiBuajq61hdWsU4Ho="
  on:
    tags: false
    branch: master

